version: "3"

services:
    express:
        build: .
        container_name: express
        volumes:
            - ./src/:/usr/app/src
        ports:
            - "8080:8080"
        depends_on:
            - "mysql"

    mysql:
        image: mysql
        restart: always
        container_name: database
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: mapit
        volumes:
            - ./.mysql:/var/lib/mysql
        # - ./database.sql:/docker-entrypoint-initdb.d
