version: "3"

services:
    express:
        # build: .
        image: node:16
        container_name: tastrServer
        volumes:
            - ./:/usr/app
        ports:
            - "8080:8080"
        working_dir: /usr/app
        depends_on:
            - "mysql"
        command: bash -c "npm install && npm run dev"
        environment:
            ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
            REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}


    mysql:
        image: mysql
        restart: always
        container_name: tastrDB
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./.mysql:/var/lib/mysql
        # - ./database.sql:/docker-entrypoint-initdb.d
